### ISSUE TITLE
LDAP configuration problem due to Docker

### ISSUE THREAD

**Issue by RadZaeem** [docker-scripts/freedombox#8]
1 year old Freedombox bug appearing in Docker
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1491373.html

After installing freedombox-setup or plinth,
LDAP configuration of Freedombox relies on policy-rc.d files.
Due to using Docker, and getting `invoke-rc.d: policy-rc.d denied execution of start.`, LDAP related packages (slapd, ldapscripts, etc) cannot be configured correctly

Workaround, **either** one of these:
1. Run plinth, wait until this error printed, then stop. then restart the container with `ds restart`. Somehow it works. Maybe LDAP is properly reconfigured in restart. If no other _proper_ solution is found, I would implement this in config.sh
2. If don't want to restart container, disable the snippet running action users in Python code in `plinth.__main__.py`. Note that this way skips Freedombox setup to support for LDAP.

Error if running `plinth` without restarting container.
action `users` of plinth will throw errors related to LDAP.
```
[2018-04-30 13:48:19,759] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'setup'], , Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.
Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.
invoke-rc.d: policy-rc.d denied execution of restart.
debconf: DbDriver "_ENV_stack": unable to save changes to: nslcd/ldap-uris nslcd/ldap-base nslcd/ldap-auth-type
Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.
/etc/nsswitch.conf: enable LDAP lookups for group
/etc/nsswitch.conf: enable LDAP lookups for passwd
/etc/nsswitch.conf: enable LDAP lookups for shadow
slapd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable slapd
nslcd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nslcd
ldap_add: Server is unwilling to perform (53)
	additional info: no global superior knowledge
Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit
    ], stdout=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapsearch', '-Q', '-Y', 'EXTERNAL', '-H', 'ldapi:///', '-s', 'base', '-b', 'ou=users,dc=thisbox', '(objectclass=*)']' returned non-zero exit status 32.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 374, in <module>
    main()
  File "/usr/share/plinth/actions/users", line 370, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup
    configure_ldap_structure()
  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure
    create_organizational_unit('users')
  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit
    stdout=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapadd', '-Q', '-Y', 'EXTERNAL', '-H', 'ldapi:///']' returned non-zero exit status 53.

[2018-04-30 13:48:19,759] plinth.setup   ERROR    Error running setup - ('users', '', 'Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ninvoke-rc.d: policy-rc.d denied execution of restart.\ndebconf: DbDriver "_ENV_stack": unable to save changes to: nslcd/ldap-uris nslcd/ldap-base nslcd/ldap-auth-type\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\n/etc/nsswitch.conf: enable LDAP lookups for group\n/etc/nsswitch.conf: enable LDAP lookups for passwd\n/etc/nsswitch.conf: enable LDAP lookups for shadow\nslapd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable slapd\nnslcd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable nslcd\nldap_add: Server is unwilling to perform (53)\n\tadditional info: no global superior knowledge\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit\n    ], stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'ou=users,dc=thisbox\', \'(objectclass=*)\']\' returned non-zero exit status 32.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 374, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 370, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup\n    configure_ldap_structure()\n  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure\n    create_organizational_unit(\'users\')\n  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit\n    stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapadd\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\']\' returned non-zero exit status 53.\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/plinth/setup.py", line 88, in run
    self.module.setup(self, old_version=current_version)
  File "/usr/local/lib/python3.6/dist-packages/plinth/modules/users/__init__.py", line 62, in setup
    helper.call('post', actions.superuser_run, 'users', ['setup'])
  File "/usr/local/lib/python3.6/dist-packages/plinth/setup.py", line 129, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/plinth/actions.py", line 118, in superuser_run
    log_error=log_error)
  File "/usr/local/lib/python3.6/dist-packages/plinth/actions.py", line 190, in _run
    raise ActionError(action, output, error)
plinth.errors.ActionError: ('users', '', 'Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ninvoke-rc.d: policy-rc.d denied execution of restart.\ndebconf: DbDriver "_ENV_stack": unable to save changes to: nslcd/ldap-uris nslcd/ldap-base nslcd/ldap-auth-type\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\n/etc/nsswitch.conf: enable LDAP lookups for group\n/etc/nsswitch.conf: enable LDAP lookups for passwd\n/etc/nsswitch.conf: enable LDAP lookups for shadow\nslapd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable slapd\nnslcd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable nslcd\nldap_add: Server is unwilling to perform (53)\n\tadditional info: no global superior knowledge\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit\n    ], stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'ou=users,dc=thisbox\', \'(objectclass=*)\']\' returned non-zero exit status 32.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 374, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 370, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup\n    configure_ldap_structure()\n  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure\n    create_organizational_unit(\'users\')\n  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit\n    stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapadd\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\']\' returned non-zero exit status 53.\n')
[2018-04-30 13:48:19,762] plinth.setup   ERROR    Error running setup - ('users', '', 'Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ninvoke-rc.d: policy-rc.d denied execution of restart.\ndebconf: DbDriver "_ENV_stack": unable to save changes to: nslcd/ldap-uris nslcd/ldap-base nslcd/ldap-auth-type\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\n/etc/nsswitch.conf: enable LDAP lookups for group\n/etc/nsswitch.conf: enable LDAP lookups for passwd\n/etc/nsswitch.conf: enable LDAP lookups for shadow\nslapd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable slapd\nnslcd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable nslcd\nldap_add: Server is unwilling to perform (53)\n\tadditional info: no global superior knowledge\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit\n    ], stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'ou=users,dc=thisbox\', \'(objectclass=*)\']\' returned non-zero exit status 32.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 374, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 370, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup\n    configure_ldap_structure()\n  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure\n    create_organizational_unit(\'users\')\n  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit\n    stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapadd\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\']\' returned non-zero exit status 53.\n')
[2018-04-30 13:48:19,762] plinth.setup   WARNING  Unable to complete setup: ('users', '', 'Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ninvoke-rc.d: policy-rc.d denied execution of restart.\ndebconf: DbDriver "_ENV_stack": unable to save changes to: nslcd/ldap-uris nslcd/ldap-base nslcd/ldap-auth-type\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\n/etc/nsswitch.conf: enable LDAP lookups for group\n/etc/nsswitch.conf: enable LDAP lookups for passwd\n/etc/nsswitch.conf: enable LDAP lookups for shadow\nslapd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable slapd\nnslcd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable nslcd\nldap_add: Server is unwilling to perform (53)\n\tadditional info: no global superior knowledge\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit\n    ], stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'ou=users,dc=thisbox\', \'(objectclass=*)\']\' returned non-zero exit status 32.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 374, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 370, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup\n    configure_ldap_structure()\n  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure\n    create_organizational_unit(\'users\')\n  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit\n    stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapadd\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\']\' returned non-zero exit status 53.\n')
[2018-04-30 13:48:19,762] plinth.setup   INFO     Will try again in 10 seconds
[2018-04-30 13:48:29,773] plinth.setup   INFO     Running first setup.
[2018-04-30 13:48:29,773] plinth.setup   INFO     Running setup for modules, essential - True, selected modules - None
[2018-04-30 13:48:29,786] plinth.setup   INFO     Running module setup - users
[2018-04-30 13:48:30,652] plinth.setup   INFO     Running step for module - users, step - post
[2018-04-30 13:48:30,653] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'first-setup']
[2018-04-30 13:48:31,022] plinth.setup   INFO     Running step for module - users, step - post
[2018-04-30 13:48:31,022] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'setup']
[2018-04-30 13:48:33,050] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'setup'], , Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.
Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.
invoke-rc.d: policy-rc.d denied execution of restart.
Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.
debconf: DbDriver "_ENV_stack": unable to save changes to: libnss-ldapd/nsswitch
slapd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable slapd
nslcd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nslcd
ldap_add: Server is unwilling to perform (53)
	additional info: no global superior knowledge
Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit
    ], stdout=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapsearch', '-Q', '-Y', 'EXTERNAL', '-H', 'ldapi:///', '-s', 'base', '-b', 'ou=users,dc=thisbox', '(objectclass=*)']' returned non-zero exit status 32.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 374, in <module>
    main()
  File "/usr/share/plinth/actions/users", line 370, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup
    configure_ldap_structure()
  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure
    create_organizational_unit('users')
  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit
    stdout=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapadd', '-Q', '-Y', 'EXTERNAL', '-H', 'ldapi:///']' returned non-zero exit status 53.

[2018-04-30 13:48:33,050] plinth.setup   ERROR    Error running setup - ('users', '', 'Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ninvoke-rc.d: policy-rc.d denied execution of restart.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ndebconf: DbDriver "_ENV_stack": unable to save changes to: libnss-ldapd/nsswitch\nslapd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable slapd\nnslcd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable nslcd\nldap_add: Server is unwilling to perform (53)\n\tadditional info: no global superior knowledge\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit\n    ], stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'ou=users,dc=thisbox\', \'(objectclass=*)\']\' returned non-zero exit status 32.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 374, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 370, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup\n    configure_ldap_structure()\n  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure\n    create_organizational_unit(\'users\')\n  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit\n    stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapadd\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\']\' returned non-zero exit status 53.\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/plinth/setup.py", line 88, in run
    self.module.setup(self, old_version=current_version)
  File "/usr/local/lib/python3.6/dist-packages/plinth/modules/users/__init__.py", line 62, in setup
    helper.call('post', actions.superuser_run, 'users', ['setup'])
  File "/usr/local/lib/python3.6/dist-packages/plinth/setup.py", line 129, in call
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/plinth/actions.py", line 118, in superuser_run
    log_error=log_error)
  File "/usr/local/lib/python3.6/dist-packages/plinth/actions.py", line 190, in _run
    raise ActionError(action, output, error)
plinth.errors.ActionError: ('users', '', 'Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ninvoke-rc.d: policy-rc.d denied execution of restart.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ndebconf: DbDriver "_ENV_stack": unable to save changes to: libnss-ldapd/nsswitch\nslapd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable slapd\nnslcd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable nslcd\nldap_add: Server is unwilling to perform (53)\n\tadditional info: no global superior knowledge\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit\n    ], stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'ou=users,dc=thisbox\', \'(objectclass=*)\']\' returned non-zero exit status 32.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 374, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 370, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup\n    configure_ldap_structure()\n  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure\n    create_organizational_unit(\'users\')\n  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit\n    stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapadd\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\']\' returned non-zero exit status 53.\n')
[2018-04-30 13:48:33,051] plinth.setup   ERROR    Error running setup - ('users', '', 'Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ninvoke-rc.d: policy-rc.d denied execution of restart.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ndebconf: DbDriver "_ENV_stack": unable to save changes to: libnss-ldapd/nsswitch\nslapd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable slapd\nnslcd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable nslcd\nldap_add: Server is unwilling to perform (53)\n\tadditional info: no global superior knowledge\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit\n    ], stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'ou=users,dc=thisbox\', \'(objectclass=*)\']\' returned non-zero exit status 32.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 374, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 370, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup\n    configure_ldap_structure()\n  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure\n    create_organizational_unit(\'users\')\n  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit\n    stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapadd\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\']\' returned non-zero exit status 53.\n')
[2018-04-30 13:48:33,051] plinth.setup   WARNING  Unable to complete setup: ('users', '', 'Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ninvoke-rc.d: policy-rc.d denied execution of restart.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ndebconf: DbDriver "_ENV_stack": unable to save changes to: libnss-ldapd/nsswitch\nslapd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable slapd\nnslcd.service is not a native service, redirecting to systemd-sysv-install.\nExecuting: /lib/systemd/systemd-sysv-install enable nslcd\nldap_add: Server is unwilling to perform (53)\n\tadditional info: no global superior knowledge\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit\n    ], stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapsearch\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\', \'-s\', \'base\', \'-b\', \'ou=users,dc=thisbox\', \'(objectclass=*)\']\' returned non-zero exit status 32.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/share/plinth/actions/users", line 374, in <module>\n    main()\n  File "/usr/share/plinth/actions/users", line 370, in main\n    subcommand_method(arguments)\n  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup\n    configure_ldap_structure()\n  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure\n    create_organizational_unit(\'users\')\n  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit\n    stdout=subprocess.DEVNULL, check=True)\n  File "/usr/lib/python3.6/subprocess.py", line 418, in run\n    output=stdout, stderr=stderr)\nsubprocess.CalledProcessError: Command \'[\'ldapadd\', \'-Q\', \'-Y\', \'EXTERNAL\', \'-H\', \'ldapi:///\']\' returned non-zero exit status 53.\n')
[2018-04-30 13:48:33,052] plinth.setup   INFO     Will try again in 10 seconds
^[[1;2A[2018-04-30 13:48:43,062] plinth.setup   INFO     Running first setup.
[2018-04-30 13:48:43,063] plinth.setup   INFO     Running setup for modules, essential - True, selected modules - None
[2018-04-30 13:48:43,073] plinth.setup   INFO     Running module setup - users
[2018-04-30 13:48:43,933] plinth.setup   INFO     Running step for module - users, step - post
[2018-04-30 13:48:43,934] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'first-setup']
[2018-04-30 13:48:44,298] plinth.setup   INFO     Running step for module - users, step - post
[2018-04-30 13:48:44,299] plinth.actions INFO     Executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'setup']
[2018-04-30 13:48:46,385] plinth.actions ERROR    Error executing command - ['sudo', '-n', '/usr/share/plinth/actions/users', 'setup'], , Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.
Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.
invoke-rc.d: policy-rc.d denied execution of restart.
Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.
debconf: DbDriver "_ENV_stack": unable to save changes to: libnss-ldapd/nsswitch
slapd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable slapd
nslcd.service is not a native service, redirecting to systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nslcd
ldap_add: Server is unwilling to perform (53)
	additional info: no global superior knowledge
Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 153, in create_organizational_unit
    ], stdout=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapsearch', '-Q', '-Y', 'EXTERNAL', '-H', 'ldapi:///', '-s', 'base', '-b', 'ou=users,dc=thisbox', '(objectclass=*)']' returned non-zero exit status 32.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/plinth/actions/users", line 374, in <module>
    main()
  File "/usr/share/plinth/actions/users", line 370, in main
    subcommand_method(arguments)
  File "/usr/share/plinth/actions/users", line 113, in subcommand_setup
    configure_ldap_structure()
  File "/usr/share/plinth/actions/users", line 142, in configure_ldap_structure
    create_organizational_unit('users')
  File "/usr/share/plinth/actions/users", line 163, in create_organizational_unit
    stdout=subprocess.DEVNULL, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ldapadd', '-Q', '-Y', 'EXTERNAL', '-H', 'ldapi:///']' returned non-zero exit status 53.

[2018-04-30 13:48:46,386] plinth.setup   ERROR    Error running setup - ('users', '', 'Use of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\nUse of uninitialized value $item in hash element at /usr/share/perl5/Debconf/DbDriver/File.pm line 85, <__ANONIO__> chunk 1.\ninvoke-rc.d: policy-rc.d denied execution of restart.\nUse  #of
```

**Comment by dashohoxha** [comment]
On the stable version this problem does not exist, as shown by the diagnostics: https://github.com/docker-scripts/freedombox/issues/3#issuecomment-385675056
